### ISSUE TITLE
Where should the trained model be placed?

### ISSUE THREAD

**Issue by yin-qiyu** [Seeed-Studio/node-red-contrib-ml#5]

**Comment by yin-qiyu** [comment]
How to deploy a trained model

**Comment by lakshanthad** [comment]
Hello @yin-qiyu,

Deploying a model using the Node-RED flow editor is a feature we will add in the future. So you will only need to upload the model file to perform the inference. 

However, for now, you need to do this manually. Please follow the steps below:

1. First of all, you need to train a model. You can follow [this section](https://wiki.seeedstudio.com/YOLOv5-Object-Detection-Jetson/#train-on-local-pc-or-cloud) of the wiki. It is better to train with either "n" or "n6" as the pre-trained weight. After training, there will be a file called "best.pt". 

2. Serialize the generated model by following [this section](https://wiki.seeedstudio.com/YOLOv5-Object-Detection-Jetson/#inference-on-jetson-device) of the wiki. Make sure to serialize to the same format as you chose during training ("n" or "n6"). After serialization, there will be a file called "best.engine". Rename this to "yolov5n.engine"

3. While the docker containers are still running, copy the serialized model file into the "node-red-contrib-ml-detection-1" container

```sh
sudo docker cp yolov5n.engine node-red-contrib-ml-detection-1:/data/build
```

4. Navigate into "node-red-contrib-ml-detection-1"

```sh
sudo docker exec -it node-red-contrib-ml-detection-1 /bin/bash
```

5. Open yolov5_trt.py inside "/data/python"

```sh
nano python/yolov5_trt.py
```

6. Change the content inside the "self.categories" list to the labels that your model can identify

7. Exit from the container

```sh
exit
```

8. Restart "node-red-contrib-ml-detection-1" container

```sh
sudo docker restart node-red-contrib-ml-detection-1
```

And you are good to go :)

Please let me know if you have any questions when following the above steps.

Thank you.

**Comment by yin-qiyu** [comment]
Thank you for your answer.
